CAMERA_INDEX = 0
WINDOW_NAME = "Real-Time Gesture Recognition"

MODEL_COMPLEXITY = 0
MAX_NUM_HANDS = 2
MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5

DISPLAY_FPS = True
DISPLAY_GESTURE = True
DISPLAY_LANDMARKS = True

ACTION_COOLDOWN_SECONDS = 1.0